-- Migration 007: Change session_code from 4 digits to 6 digits
-- session_code column is already TEXT so no type change needed.
-- Backfill any existing 4-digit codes to 6 digits (for open sessions in dev).
-- New sessions generated by application will produce 6-digit codes (100000–999999).

UPDATE crs_sessions
SET session_code = LPAD((FLOOR(100000 + RANDOM() * 900000))::text, 6, '0')
WHERE length(session_code) < 6;
